baldo:
  scheduler: slurm

  default_conf:
    partition: edu-short
    nodes: 1
    ntasks: 1
    gpus: 0

  configs:
    - name: 1cpu
      env:
        - "OMP_NUM_THREADS=1"
      cpus-per-task: 1
    - name: 2cpu
      env:
        - "OMP_NUM_THREADS=2"
      cpus-per-task: 2
    - name: 4cpu
      env:
        - "OMP_NUM_THREADS=4"
      cpus-per-task: 4

local:
  scheduler: local
  configs:
    - name: 1cpu
      env:
        - "OMP_NUM_THREADS=1"
    - name: 2cpu
      env:
        - "OMP_NUM_THREADS=2"
    - name: 4cpu
      env:
        - "OMP_NUM_THREADS=4"
