in_img_path = "./examples/sample_flower.jpg"
original_csv_path = "./data/original.csv"
modified_csv_path = "./data/modified.csv"
out_img_path = "./data/reconstructed.jpg"
metrics_path = "./data/perf_results.txt"
